version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www

  php:
    build:
      context: ./docker/php
    restart: always
    volumes:
      - ./:/var/www
    depends_on:
      - nginx
  db:
    image: mysql:latest
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
